# SPDX-FileCopyrightText: Andrei Gherzan <andrei.gherzan@huawei.com>
#
# SPDX-License-Identifier: MIT

name: Mirrors

on: [ push, delete, create ]

concurrency:
  group: git-mirror-me

jobs:
  yocto-mirror:
    name: Yocto Git Mirror
    runs-on: [self-hosted, Linux]
    steps:
      - uses: agherzan/git-mirror-me-action@v2.0.1
        with:
          destination-repository: "git@push.yoctoproject.org:meta-raspberrypi"
          debug: "true"
